flag_management:
  individual_flags:
    - name: flexicart
      paths:
        - packages/flexi_cart/**
    - name: filterator
      paths:
        - packages/filterator/**
    - name: unsaved_changes
      paths:
        - packages/unsaved_changes/**
    - name: unsaved_changes_forms
      paths:
        - packages/unsaved_changes_forms/**
    - name: currency_kit
      paths:
        - packages/currency_kit/**
