flag_management:
  individual_flags:
    - name: flexicart
      paths:
        - packages/flexi_cart/**
    - name: filterator
      paths:
        - packages/filterator/**
    - name: unsaved_changes
      paths:
        - packages/unsaved_changes/**
    - name: unsaved_changes_forms
      paths:
        - packages/unsaved_changes_forms/**
    - name: batch_fetcher
      paths:
        - packages/batch_fetcher/**
    - name: batch_fetcher_flutter
      paths:
        - packages/batch_fetcher_flutter/**
