name: unleash_client
description: A Server Side Dart SDK for Unleash. Unleash is an open-source feature flag service.
version: 0.4.7
repository: https://github.com/supy-io/supy-flutter-packages

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  meta: ^1.16.0
  http: ^1.2.2
  path: ^1.9.1

dev_dependencies:
  coverage: ^1.11.1
  test: ^1.25.14
  yaml: ^3.1.3
  lints: ^5.1.1
