name: example
description: A new example project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  unleash_client:
    path: ../../unleash_client

dev_dependencies:
  lints: ^1.0.0