name: unsaved_changes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'packages/unsaved_changes/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/unsaved_changes/**'
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.19.0

      - name: Install Dependencies
        run: flutter packages get
        working-directory: packages/unsaved_changes

      - name: Format
        run: dart format --set-exit-if-changed .
        working-directory: packages/unsaved_changes

      - name: Analyze
        run: flutter analyze lib test example
        working-directory: packages/unsaved_changes

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
        working-directory: packages/unsaved_changes

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3
        with:
          path: packages/unsaved_changes/coverage/lcov.info
          min_coverage: 85
          # exclude: '**/*_observer.dart **/change.dart'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: packages/unsaved_changes/coverage/lcov.info
          flags: unsaved_changes
