name: filterator
description: API Query Builder for Dart – A powerful, flexible library for building structured API queries with filtering, sorting, pagination, and easy conversion to API-specific formats.


version: 0.1.1-beta.1
repository: https://github.com/supy-io/supy-flutter-packages/tree/main/packages/filterator
issue_tracker: https://github.com/supy-io/supy-flutter-packages/issues
homepage: https://github.com/supy-io/supy-flutter-packages/tree/main/packages/filterator
topics: [ query-builder, query-interface,filtering,pagination ]

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  meta: ^1.17.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.1
  mockito: ^5.4.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  very_good_analysis: ^7.0.0


example: example/main.dart
